import fs from 'node:fs'; import { test } from 'node:test'; import assert from 'node:assert/strict';
const wpis=fs.readFileSync('collection/entries/373dsk-fear-of-abduction.md','utf8'); const karta=fs.readFileSync('content/cards/373dsk-fear-of-abduction.md','utf8'); const snap=JSON.parse(fs.readFileSync('scryfall/373dsk-fear-of-abduction.json')); const mapa=JSON.parse(fs.readFileSync('maps/duskmourn/map.json')); const svg=fs.readFileSync('maps/duskmourn/podklad.svg','utf8');
const fabula='W sypialni na opustoszałych przedmieściach Duskmourn, manifestacja czystego strachu narusza cienką barierę między snem a jawą. Z pustego łóżka unosi się jeszcze echo strachu dziecka, które stało się ofiarą-kotwicą, by przywołać ten koszmar do istnienia. Teraz, zrodzony z tego lęku byt unosi wrogiego żołnierza ku wirującemu w suficie obliczu, wciągając go w nicość, z której nie ma powrotu na pole bitwy. Gdy koszmar wreszcie przeminie, obie porwane dusze powrócą, lecz odmienione tym doświadczeniem, na zawsze naznaczone wspomnieniem uprowadzenia.';
test('373DSK: Fabuła właściciela pozostaje verbatim',()=>assert.equal(wpis.match(/^---\n[\s\S]*?\n---\n\n([\s\S]*?)\n?$/)?.[1],fabula));
test('373DSK: imgId pozostaje niezależny od DSK #9',()=>{assert.equal(snap.collector_number,'9');assert.match(snap.notka_numery,/373DSK/)});
test('373DSK: mechanika zachowuje dwie ofiary i wspólny powrót',()=>{assert.equal(snap.mana_cost,'{4}{W}{W}');assert.equal(snap.power,'5');assert.equal(snap.toughness,'5');assert.match(snap.oracle_text,/additional cost[\s\S]*exile a creature you control/);assert.match(snap.oracle_text,/exile target creature an opponent controls/);assert.match(snap.oracle_text,/each card exiled with it into its owner's hand/)});
test('373DSK: nicość nie zostaje utożsamiona z The Below',()=>{assert.match(karta,/Nie utożsamiamy jej z \*\*The\nBelow\*\*/);assert.match(karta,/powrót do ręki/);assert.match(karta,/dziecko-kotwica/)});
test('Duskmourn: mapa jest diagramem antykartograficznym',()=>{assert.equal(mapa.wariant,'T4');assert.match(mapa.uklad_wspolrzednych,/nigdy fizyczną pozycję/);assert.doesNotMatch(svg,/kompas|skala 1:/i);for(const n of ['Mistmoors','Floodpits','Balemurk','Boilerbilges','Hauntwoods','The Below'])assert.ok(mapa.kotwice.some(x=>x.nazwa===n),n);assert.match(svg,/tylko oś piwnica → The Below jest stała/)});
test('373DSK: pinezka jest przybliżona w zmiennych pokojach',()=>{const p=mapa.pinezki.find(x=>x.karta==='373dsk-fear-of-abduction');const a=mapa.kotwice.find(x=>x.nazwa==='Zmienne pokoje Domu');assert.ok(p);assert.equal(p.pewnosc,'przyblizona');assert.equal(p.x,a.x);assert.equal(p.y,a.y);assert.match(p.uzasadnienie,/nie tworzy ulicy/)});
