import fs from 'node:fs'; import { test } from 'node:test'; import assert from 'node:assert/strict';
const wpis=fs.readFileSync('collection/entries/385dka-midnight-guard.md','utf8'); const karta=fs.readFileSync('content/cards/385dka-midnight-guard.md','utf8'); const snap=JSON.parse(fs.readFileSync('scryfall/385dka-midnight-guard.json')); const mapa=JSON.parse(fs.readFileSync('maps/innistrad/map.json')); const haslo=fs.readFileSync('content/lore/nephalia.md','utf8');
const fabula='Na drewnianej palisadzie wioski Skiltfolk nad jeziorem Zhava w Nephalii strażnik Północy odwraca się gwałtownie, gdy ciężka brama otwiera się przed kolejnym przybyszem. Jego halabarda z symbolem Kościoła Avacyn lśni w świetle żelaznej pochodni, a płaszcz z wilczej skóry jest mokry od mgły, która od zniknięcia Anielskiej opiekunki zalega nad całą prowincją. W tle, pod bladym światłem srebrnego księżyca, majaczą spiczaste dachy Thraben i ciche wody Gavony. Olgard ze Skiltfolk uczył wtedy swoich ludzi, że na warcie żaden szmer nie jest niewinny i żaden cień nie może zostać zignorowany.';
test('385DKA: Fabuła właściciela pozostaje verbatim',()=>assert.equal(wpis.match(/^---\n[\s\S]*?\n---\n\n([\s\S]*?)\n?$/)?.[1],fabula));
test('385DKA: imgId pozostaje niezależny od DKA #14',()=>{assert.equal(snap.collector_number,'14');assert.match(snap.notka_numery,/385DKA/)});
test('385DKA: 2/3 i odtapowanie po każdej innej istocie',()=>{assert.equal(snap.mana_cost,'{2}{W}');assert.equal(snap.power,'2');assert.equal(snap.toughness,'3');assert.equal(snap.oracle_text,'Whenever another creature enters, untap this creature.');assert.match(snap.flavor_text,/Olgard of the Skiltfolk/)});
test('385DKA: lore nie przenosi Thraben nad Zhavę',()=>{assert.match(karta,/bezimiennej osadzie/);assert.match(karta,/nie czynimy jednak przedmieściem/);assert.match(karta,/daleką stolicą/);assert.match(karta,/\[\[nephalia\|Nephalii\]\]/)});
test('385DKA: pinezka regionalna na Lake Zhava',()=>{const p=mapa.pinezki.find(x=>x.karta==='385dka-midnight-guard');const a=mapa.kotwice.find(x=>x.nazwa==='Lake Zhava');assert.ok(p);assert.equal(p.pewnosc,'region');assert.equal(p.x,a.x);assert.equal(p.y,a.y);assert.match(a.pozycja_zrodlo,/Sacrifice/)});
test('385DKA: Nephalia przekracza próg dwóch kart',()=>{assert.match(haslo,/309isd-civilized-scholar/);assert.match(haslo,/385dka-midnight-guard/)});
